spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:h2:mem:mino
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
